// Map of states to their nearby states that are typically within commuting distance
export const nearbyStates = {
  'NY': ['NJ', 'CT', 'PA', 'MA', 'RI', 'VT'],
  'NJ': ['NY', 'PA', 'DE', 'CT', 'MD'],
  'CT': ['NY', 'MA', 'RI', 'NJ', 'VT', 'NH'],
  'MA': ['NH', 'RI', 'CT', 'VT', 'NY', 'ME'],
  'PA': ['NJ', 'NY', 'DE', 'MD', 'WV', 'OH'],
  'RI': ['MA', 'CT', 'NY', 'NH'],
  'NH': ['MA', 'ME', 'VT', 'RI', 'CT'],
  'VT': ['NY', 'NH', 'MA', 'CT'],
  'ME': ['NH', 'MA'],
  'DE': ['NJ', 'PA', 'MD'],
  'MD': ['PA', 'DE', 'NJ', 'WV', 'VA', 'DC'],
  'DC': ['MD', 'VA'],
  'VA': ['MD', 'DC', 'NC', 'WV', 'KY', 'TN'],
  'WV': ['PA', 'MD', 'VA', 'KY', 'OH'],
  'OH': ['PA', 'WV', 'KY', 'IN', 'MI'],
  'MI': ['OH', 'IN', 'WI', 'IL'],
  'IN': ['OH', 'KY', 'IL', 'MI'],
  'IL': ['WI', 'IN', 'KY', 'MO', 'IA'],
  'WI': ['MI', 'IL', 'MN', 'IA'],
  'MN': ['WI', 'IA', 'ND', 'SD'],
  'IA': ['WI', 'IL', 'MO', 'MN', 'SD', 'NE'],
  'MO': ['IA', 'IL', 'KY', 'TN', 'AR', 'OK', 'KS', 'NE'],
  'KY': ['OH', 'WV', 'VA', 'TN', 'MO', 'IL', 'IN'],
  'TN': ['KY', 'VA', 'NC', 'GA', 'AL', 'MS', 'AR', 'MO'],
  'NC': ['VA', 'TN', 'GA', 'SC'],
  'SC': ['NC', 'GA'],
  'GA': ['NC', 'SC', 'FL', 'AL', 'TN'],
  'FL': ['GA', 'AL'],
  'AL': ['GA', 'FL', 'MS', 'TN'],
  'MS': ['AL', 'TN', 'AR', 'LA'],
  'AR': ['MO', 'TN', 'MS', 'LA', 'TX', 'OK'],
  'LA': ['AR', 'MS', 'TX'],
  'TX': ['LA', 'AR', 'OK', 'NM'],
  'OK': ['KS', 'MO', 'AR', 'TX', 'NM', 'CO'],
  'KS': ['NE', 'MO', 'OK', 'CO'],
  'NE': ['SD', 'IA', 'MO', 'KS', 'CO', 'WY'],
  'SD': ['ND', 'MN', 'IA', 'NE', 'WY', 'MT'],
  'ND': ['MN', 'SD', 'MT'],
  'MT': ['ND', 'SD', 'WY', 'ID'],
  'WY': ['MT', 'SD', 'NE', 'CO', 'UT', 'ID'],
  'CO': ['WY', 'NE', 'KS', 'OK', 'NM', 'UT'],
  'NM': ['CO', 'OK', 'TX', 'AZ'],
  'AZ': ['CA', 'NV', 'UT', 'NM'],
  'UT': ['ID', 'WY', 'CO', 'NM', 'AZ', 'NV'],
  'NV': ['OR', 'ID', 'UT', 'AZ', 'CA'],
  'ID': ['WA', 'MT', 'WY', 'UT', 'NV', 'OR'],
  'CA': ['OR', 'NV', 'AZ'],
  'OR': ['WA', 'ID', 'NV', 'CA'],
  'WA': ['OR', 'ID']
};

// Function to get nearby states including the original state
export const getNearbyStates = (stateCode) => {
  const upperStateCode = stateCode.toUpperCase();
  if (!nearbyStates[upperStateCode]) {
    return [upperStateCode];
  }
  return [upperStateCode, ...nearbyStates[upperStateCode]];
};

// Helper function to convert state name to abbreviation
export const getStateAbbreviation = (stateName) => {
  const stateMap = {
    'new york': 'NY',
    'new jersey': 'NJ',
    'connecticut': 'CT',
    'pennsylvania': 'PA',
    'massachusetts': 'MA',
    'rhode island': 'RI',
    'new hampshire': 'NH',
    'vermont': 'VT',
    'maine': 'ME',
    'delaware': 'DE',
    'maryland': 'MD',
    'district of columbia': 'DC',
    'virginia': 'VA',
    'west virginia': 'WV',
    'ohio': 'OH',
    'michigan': 'MI',
    'indiana': 'IN',
    'illinois': 'IL',
    'wisconsin': 'WI',
    'minnesota': 'MN',
    'iowa': 'IA',
    'missouri': 'MO',
    'kentucky': 'KY',
    'tennessee': 'TN',
    'north carolina': 'NC',
    'south carolina': 'SC',
    'georgia': 'GA',
    'florida': 'FL',
    'alabama': 'AL',
    'mississippi': 'MS',
    'arkansas': 'AR',
    'louisiana': 'LA',
    'texas': 'TX',
    'oklahoma': 'OK',
    'kansas': 'KS',
    'nebraska': 'NE',
    'south dakota': 'SD',
    'north dakota': 'ND',
    'montana': 'MT',
    'wyoming': 'WY',
    'colorado': 'CO',
    'new mexico': 'NM',
    'arizona': 'AZ',
    'utah': 'UT',
    'nevada': 'NV',
    'idaho': 'ID',
    'california': 'CA',
    'oregon': 'OR',
    'washington': 'WA',
    'washington dc': 'DC'
  };
  
  return stateMap[stateName.toLowerCase()] || stateName.toUpperCase();
};